In [0]:
import nltk 
nltk.download('all')

In [0]:
import numpy as np
from nltk.corpus import stopwords
from nltk import pos_tag
from nltk.stem import WordNetLemmatizer
import string
from nltk.corpus import wordnet
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
from nltk.tokenize import sent_tokenize,word_tokenize
from sklearn import ensemble
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.linear_model import LogisticRegression
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
import csv
from sklearn.model_selection import cross_val_score


In [7]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 0000000000002747_training_twitter_x_y_train.csv to 0000000000002747_training_twitter_x_y_train.csv
User uploaded file "0000000000002747_training_twitter_x_y_train.csv" with length 2158741 bytes


In [8]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

Saving 0000000000002747_test_twitter_x_test.csv to 0000000000002747_test_twitter_x_test.csv
User uploaded file "0000000000002747_test_twitter_x_test.csv" with length 747871 bytes


In [0]:
def loading():
#     data_training=pd.read_csv('G:\Development\Projects\Python Projects\Machine_Learning\\NLP\\NLP_Project\\0000000000002747_training_twitter_x_y_train.csv',header=None)
#     data_test=pd.read_csv('G:\Development\Projects\Python Projects\Machine_Learning\\NLP\\NLP_Project\\0000000000002747_test_twitter_x_test.csv',header=None)
  data_test=pd.read_csv('0000000000002747_test_twitter_x_test.csv',header=None)
  data_training=pd.read_csv('0000000000002747_training_twitter_x_y_train.csv',header=None)
  data_training.columns=['tweet_id',
                           'airline_sentiment',
                           'airline',
                           'airline_sentiment_gold',
                           'name',
                           'negativereason_gold',
                           'retweet_count',
                           'text',
                           'tweet_coord',
                           'tweet_created',
                           'tweet_location',
                           'user_timezone'
                           ]
  data_test.columns =     ['tweet_id',
                             'airline',
                             'airline_sentiment_gold',
                             'name',
                             'negativereason_gold',
                             'retweet_count',
                             'text',
                             'tweet_coord',
                             'tweet_created',
                             'tweet_location',
                             'user_timezone'
                             ]

  return data_training,data_test

In [10]:
data_train,data_test=loading()
y_categories=data_train['airline_sentiment']
del data_train['airline_sentiment']
data_train

tweet_id     airline  airline_sentiment_gold             name  \
0         tweet_id     airline  airline_sentiment_gold             name   
1        5.679E+17   Southwest                     NaN    ColeyGirouard   
2      5.69989E+17   Southwest                     NaN    WalterFaddoul   
3      5.68089E+17      United                     NaN        LocalKyle   
4      5.68928E+17   Southwest                     NaN      amccarthy19   
5      5.68594E+17      United                     NaN          J_Okayy   
6      5.69678E+17      United                     NaN       bobgiolito   
7      5.69659E+17       Delta                     NaN     aaronkinnari   
8      5.68543E+17       Delta                     NaN      TimothySays   
9      5.70116E+17      United                     NaN         lindaSWC   
10      5.6887E+17   Southwest                     NaN           amyums   
11     5.67794E+17   Southwest                     NaN          Faultie   
12     5.69879E+17       Delta                     NaN        tonymbove   
13     5.68518E+17  US Airways                     NaN      sherrylweir   
14     5.68213E+17   Southwest                     NaN        Mselite25   
15      5.6927E+17  US Airways                     NaN     KennethBracy   
16     5.67817E+17  US Airways                     NaN       SyncSummit   
17      5.6969E+17    American                     NaN    Lioninflorida   
18     5.69933E+17       Delta                     NaN          TheBuie   
19     5.69939E+17       Delta                     NaN        TheRealOx   
20     5.69958E+17    American                     NaN       Rizzilient   
21     5.68361E+17  US Airways                     NaN  TomFutureforall   
22     5.68127E+17   Southwest                     NaN     DoctorFox007   
23     5.68884E+17  US Airways                     NaN   chrisseifert83   
24     5.70056E+17      United                     NaN    JeffPKirkland   
25     5.68804E+17      United                     NaN    jonatzzValdez   
26     5.67925E+17      United                     NaN         MusseZam   
27     5.68434E+17       Delta                     NaN        Old_bauer   
28     5.70083E+17      United                     NaN        KeenanPam   
29     5.68585E+17   Southwest                     NaN      Salem_Eways   
...            ...         ...                     ...              ...   
10951  5.69126E+17       Delta                     NaN  Dress4YesConJax   
10952  5.69683E+17   Southwest                     NaN     horacioguapo   
10953  5.69372E+17   Southwest                     NaN    Angela_Meyers   
10954  5.69334E+17      United                     NaN         Jo_Frost   
10955  5.68427E+17   Southwest                     NaN     thirty_lives   
10956  5.70018E+17       Delta                     NaN        4TONEMENT   
10957  5.68118E+17   Southwest                     NaN       BobbiStorm   
10958  5.68523E+17  US Airways                     NaN      VirginiaRmz   
10959  5.70291E+17      United                     NaN         nate2482   
10960  5.69624E+17  US Airways                     NaN       dave_cavan   
10961  5.68842E+17      United                     NaN     iamawarplane   
10962  5.69263E+17       Delta                     NaN          rosenrj   
10963  5.69308E+17      United                     NaN         gwen1013   
10964  5.69369E+17  US Airways                     NaN      dailylaurel   
10965  5.69009E+17      United                     NaN      johnwoodRTR   
10966  5.70165E+17      United                     NaN      8629Fissile   
10967  5.68417E+17      United                     NaN          Brennej   
10968  5.67617E+17   Southwest                     NaN      mrshossruns   
10969  5.69665E+17    American                     NaN   vickie_frisbie   
10970  5.68531E+17   Southwest                     NaN      stefughknee   
10971  5.70283E+17   Southwest                     NaN        slobotski   
10972  5.69087E+17       Delta     

In [0]:
def count_types_output(y):              # This function calculates the different types of
    a=[]                                # outputs that are present in the output column.
    for i in y:                         # eg:- It will calculate and result [0,1](malignant/bennie) for cancer
        if i in a:                      # data set and [0,1](survived/not survived) for the titanic data set.
            continue
        else:
            a.append(i)
    return a


def output_counter(y):                              # This function calculates the number of occurrences of the
    output_label = count_types_output(y)            # different types of outputs present in the output column.
    output_label=np.array(output_label)
    # print(output_label.shape)
    label_count = np.zeros(output_label.shape)
    for i in range(0,len(y)):
        for j in range(len(output_label)):
            if y[i] == output_label[j]:
                label_count[j] = label_count[j] + 1
    # print(label_count)
    dict={}
    for i in range(len(label_count)):
        dict[output_label[i]]=label_count[i]
    return dict

def makeLabelled(column,dict):
    labels=dict.keys()
    new_labels=[i for i in labels]
    # print(new_labels)
    new_column=[]
    for i in range(len(new_labels)):
        if new_labels[i]=='nan':
            nan_index=i
            break
    # print(nan_index)
    column.fillna('nothing',inplace=True)
    for i in range(len(column)):
        if column[i]=='nothing':
            # print(column[i])
            new_column.append(nan_index)
        else:
            for j in range(len(new_labels)):
                if column[i]==new_labels[j]:
                    # print(column[i])
                    new_column.append(j)
                    break
    return new_column

In [0]:

def data_cleaning(data):
    del data['tweet_id']
    del data['name']
    del data['negativereason_gold']
    del data['tweet_created']
    del data['tweet_coord']
    del data['tweet_location']

    dict_airline=(output_counter(data['airline']))
    new_airline=makeLabelled(data['airline'],dict_airline)
    dict_gold_cust = (output_counter(data['airline_sentiment_gold']))
    new_gold_cust=makeLabelled(data['airline_sentiment_gold'],dict_gold_cust)
    dict_timezone=output_counter(data['user_timezone'])
    new_timezone=makeLabelled(data['user_timezone'],dict_timezone)
    return new_airline,new_gold_cust,new_timezone


In [0]:
new_airline_train,new_gold_cust_train,new_timezone_train=data_cleaning(data_train)
new_airline_test,new_gold_cust_test,new_timezone_test=data_cleaning(data_test)

In [0]:

def pos_to_wordnet(pos_tag):
    # print(pos_tag)
    if pos_tag.startswith('J'):
        return wordnet.ADJ
    elif pos_tag.startswith('N'):
        return wordnet.NOUN
    elif pos_tag.startswith('V'):
        return wordnet.VERB
    elif pos_tag.startswith('R'):
        return wordnet.ADJ
    else:
        return wordnet.NOUN


def cleaning_words(words):
    words=word_tokenize(words.lower())
    word_array=[]
    lemmatizer = WordNetLemmatizer()
    stop_words = stopwords.words('english')
    punctuations = list(string.punctuation)
    stop_words += punctuations
    for i in range(len(words)):
        if words[i] in stop_words:
            continue
        else:
            pos_tuple_returned=pos_tag([words[i]])
            word=lemmatizer.lemmatize(words[i],pos=pos_to_wordnet(pos_tuple_returned[0][1]))
            word_array.append(word)
    return word_array


def cleaning_file(document):
    cleaned_words=[]
    for i in range(len(document)):
        new_array=cleaning_words(document[i])
        cleaned_words.append(new_array)
    return cleaned_words


In [0]:

def tweet_cleaning(data):
    text=data['text']
    cleaned_text=cleaning_file(text)
    return cleaned_text

In [0]:
cleaned_text_train=tweet_cleaning(data_train)
cleaned_text_test=tweet_cleaning(data_test)

In [0]:
def creating_sentences(x_y_train):
    x_train_sentences=[]
    for i in range(len(x_y_train)):
        x_train_sentences.append(" ".join(x_y_train[i]))
    return x_train_sentences

In [0]:
x_train_text_sentences=creating_sentences(cleaned_text_train)
x_test_text_sentences=creating_sentences(cleaned_text_test)

In [0]:
def count_vectorize(x_train_sentences,x_test_sentences):
    count_vec=CountVectorizer(max_features=2500,ngram_range=(1,4))
    x_train_features=count_vec.fit_transform(x_train_sentences)
#     print(count_vec.get_feature_names())
    x_train_features=x_train_features.todense()
    x_test_features=count_vec.transform(x_test_sentences)
    x_test_features=x_test_features.todense()
    return x_train_features,x_test_features,count_vec.get_feature_names()


In [0]:
x_train_features,x_test_features,feature_names=count_vectorize(x_train_text_sentences,x_test_text_sentences)

In [0]:
x_train=pd.DataFrame(x_train_features,columns=feature_names)
x_test=pd.DataFrame(x_test_features,columns=feature_names)

In [0]:
x_test['new_airline']=new_airline_test
x_test['new_gold_cust']=new_gold_cust_test
x_test['new_timezone']=new_timezone_test
x_train['new_airline']=new_airline_train
x_train['new_gold_cust']=new_gold_cust_train
x_train['new_timezone']=new_timezone_train

In [0]:
from sklearn.model_selection import train_test_split
x_train, x_test_not_actual, y_train, y_test_not_actual =train_test_split(x_train,y_categories)

In [84]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test_not_actual)
from  sklearn.metrics import confusion_matrix,classification_report
print(classification_report(y_test_not_actual,y_pred))
print(confusion_matrix(y_test_not_actual,y_pred))


             precision    recall  f1-score   support

   negative       0.80      0.88      0.84      1698
    neutral       0.54      0.47      0.51       575
   positive       0.69      0.55      0.61       473

avg / total       0.73      0.74      0.73      2746

[[1496  138   64]
 [ 252  273   50]
 [ 121   94  258]]


In [85]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred = lr.predict(x_test_not_actual)
print("Logistic Regression.................................")
print(classification_report(y_test_not_actual, y_pred))
print(confusion_matrix(y_test_not_actual, y_pred))
    

Logistic Regression.................................
             precision    recall  f1-score   support

   negative       0.84      0.89      0.86      1698
    neutral       0.61      0.58      0.60       575
   positive       0.79      0.66      0.72       473

avg / total       0.78      0.78      0.78      2746

[[1508  146   44]
 [ 198  336   41]
 [  92   70  311]]


In [0]:
clf = SVC(kernel = 'linear')
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test_not_actual)
print("SVM.................................")
print(classification_report(y_test_not_actual, y_pred))
print(confusion_matrix(y_test_not_actual, y_pred))
  

In [0]:
x_axis = []
y_axis = []
for i in range(1, 26, 2):
  clf = KNeighborsClassifier(n_neighbors = i)
  score = cross_val_score(clf, x_train, y_train)
  x_axis.append(i)
  y_axis.append(score.mean())
max_score=(max(y_axis))
for i in range(len(y_axis)):
  if y_axis[i]==max_score:
      val=x_axis[i]
neigh=KNeighborsClassifier(n_neighbors = val)
neigh.fit(x_train, y_train)
y_pred = neigh.predict(x_test_not_actual)
print("KNN.................................")
print(classification_report(y_test_not_actual, y_pred))
print(confusion_matrix(y_test_not_actual, y_pred))
  

In [69]:
deci=DecisionTreeClassifier()
deci.fit(x_train,y_train)
y_pred = deci.predict(x_test_not_actual)
print("Decision Tree............................")
print(classification_report(y_test_not_actual,y_pred))
print(confusion_matrix(y_test_not_actual,y_pred))

Decision Tree............................
             precision    recall  f1-score   support

   negative       0.65      0.95      0.77      1740
    neutral       0.39      0.11      0.17       555
   positive       0.22      0.03      0.06       451

avg / total       0.53      0.63      0.53      2746

[[1649   52   39]
 [ 483   59   13]
 [ 395   41   15]]


In [0]:
y_final_1=rf.predict(x_test)
y_final_2=lr.predict(x_test)
y_final_3=clf.predict(x_test)
y_final_4=neigh.predict(x_test)
y_final_5=deci.predict(x_test)


In [0]:

with open('submission_1.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_1)):
      spamwriter.writerow(y_final_1[i])

with open('submission_2.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_2)):
      spamwriter.writerow(y_final_2[i])

with open('submission_3.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_3)):
      spamwriter.writerow(y_final_3[i])

with open('submission_4.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_4)):
      spamwriter.writerow(y_final_4[i])


with open('submission_5.csv', 'w') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter='\n')
    for i in range(len(y_final_5)):
      spamwriter.writerow(y_final_5[i])

files.download('submission_1.csv')
files.download('submission_2.csv')
files.download('submission_3.csv')
files.download('submission_4.csv')
files.download('submission_5.csv')
